### ISSUE TITLE
Add strip preffix feature

### ISSUE THREAD

**Issue by pkucmus** [mirumee/smyth#10]
When using a config like this

```toml
[tool.smyth]
host = "0.0.0.0"
port = 8080

[tool.smyth.handlers.other_handler]
handler_path = "my_project.app.other_handler"
url_path = "/other/{path:path}"
timeout = 500

[tool.smyth.handlers.root_handler]
handler_path = "my_project.app.handler"
url_path = "/{path:path}"
timeout = 500
```

The `other_handler` handler receives the full path `/other/{path:path}` while I would like to have the option for it to be unaware of the `/other` part of the path.

So I suggest we add a `strip_prefix` option to the HandlerConfig which would let the event builder know to strip it from the `rawPath` and `path`: https://github.com/mirumee/smyth/blob/725c856c023fc2e08f6e78dd530e123c7c1713c6/src/smyth/event.py#L10-L18
