### ISSUE TITLE
Check and potentially bump CI/CD actions.

### ISSUE THREAD

**Issue by pkucmus** [mirumee/smyth#17]
There is [an issue](https://github.com/sigstore/gh-action-sigstore-python/issues/159) with sigstore/gh-action-sigstore-python@v2, sigstore/gh-action-sigstore-python@v3 works

And we seem to be missing the `contents: write` permission (which was never before required), update to `softprops/action-gh-release@v2` while we're at it.

prepare_release.yml
```yaml
...
  create-release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
...
```
